name: tests
run-name: testing in node
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: create env file
        run: |
          touch .env
          echo "NODE_ENV=\"CI\"" >> .env
      - name: npm install, build
        run: |
          NPM_CONFIG_PRODUCTION=false npm install
          npm run build --if-present
          npx playwright install --with-deps
        env:
          CI: true
      - name: Run tap tests
        env:
          DISPLAY: ":99"
          FIREFOX_DISABLE_SANDBOX: 1
        run: |
          xvfb-run --server-args="-screen 0 1920x1080x24 -ac +extension GLX +render -noreset" npm test
